version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      # Add any additional environment variables here
    depends_on:
      - cms
    restart: unless-stopped

  cms:
    build:
      context: .
      dockerfile: Dockerfile.cms
    ports:
      - "1337:1337"
    environment:
      - NODE_ENV=production
      # Add any additional environment variables here
    volumes:
      - cms_data:/app/database
    restart: unless-stopped

volumes:
  cms_data: # This will persist the CMS database between container restarts 
