version: '3'

services:
  cms:
    build:
      context: ./apps/cms
      dockerfile: Dockerfile
    container_name: yapo-cms
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DATABASE_CLIENT: sqlite
      DATABASE_FILENAME: .tmp/data.db
    env_file:
      - ./apps/cms/.env
    volumes:
      - cms_data:/app/.tmp
    ports:
      - "1337:1337"
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:1337/admin"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    container_name: yapo-web
    restart: unless-stopped
    environment:
      NODE_ENV: production
      STRAPI_URL: http://cms:1337
    env_file:
      - ./apps/web/.env
    ports:
      - "3000:3000"
    depends_on:
      cms:
        condition: service_healthy

volumes:
  cms_data: 