name: Build and Push Docker Images

on:
  push:
    branches:
      - main
    paths:
      - 'apps/**'
      - 'Dockerfile.*'
      - 'package.json'
      - 'yarn.lock'
      - '.github/workflows/docker-build-push.yml'
  workflow_dispatch:

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      web_changed: ${{ steps.filter.outputs.web_changed }}
      cms_changed: ${{ steps.filter.outputs.cms_changed }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for file changes
      
      - name: Check for changes
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            web_changed:
              - 'apps/web/**'
              - 'Dockerfile.web'
              - 'package.json'
              - 'yarn.lock'
              - '.yarnrc.yml'
            cms_changed:
              - 'apps/cms/**'
              - 'Dockerfile.cms'
              - 'package.json'
              - 'yarn.lock'
              - '.yarnrc.yml'

  build-and-push:
    needs: detect-changes
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        if: needs.detect-changes.outputs.web_changed == 'true' || needs.detect-changes.outputs.cms_changed == 'true'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        if: needs.detect-changes.outputs.web_changed == 'true' || needs.detect-changes.outputs.cms_changed == 'true'

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        if: needs.detect-changes.outputs.web_changed == 'true' || needs.detect-changes.outputs.cms_changed == 'true'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Web Image
        uses: docker/build-push-action@v5
        if: needs.detect-changes.outputs.web_changed == 'true'
        with:
          context: .
          file: ./Dockerfile.web
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/yapp-web:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/yapp-web:latest
          cache-to: type=inline

      - name: Build and Push CMS Image
        uses: docker/build-push-action@v5
        if: needs.detect-changes.outputs.cms_changed == 'true'
        with:
          context: .
          file: ./Dockerfile.cms
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/yapp-cms:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/yapp-cms:latest
          cache-to: type=inline 